export const PERMISSOES = {
  CADASTRAR_USUARIOS: 'CADASTRAR_USUARIOS',
  CADASTRAR_LIVROS: 'CADASTRAR_LIVROS',
  LOCAR_LIVROS: 'LOCAR_LIVROS',
  DEVOLVER_LIVROS: 'DEVOLVER_LIVROS',
  EXCLUIR_LIVROS: 'EXCLUIR_LIVROS',
  ACESSAR_DASHBOARD: 'ACESSAR_DASHBOARD',
} as const;

export type NomePermissao = (typeof PERMISSOES)[keyof typeof PERMISSOES];

export const PERMISSOES_PADRAO_USUARIO: NomePermissao[] = [
  PERMISSOES.LOCAR_LIVROS,
  PERMISSOES.DEVOLVER_LIVROS,
  PERMISSOES.ACESSAR_DASHBOARD,
];
